
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xba\x8f\x94\xe3\x8aa\x95kR\xe6-\xe9H\xea\x0b\xf7'
    
_lr_action_items = {'GEQ':([1,2,14,15,16,17,19,],[-6,5,-4,-5,-7,-9,-8,]),'NUMBER':([0,5,6,7,8,9,],[4,11,12,13,4,4,]),'TIMES':([4,16,17,19,],[10,18,-9,-8,]),'LEQ':([1,2,14,15,16,17,19,],[-6,7,-4,-5,-7,-9,-8,]),'PLUS':([1,2,14,15,16,17,19,],[-6,8,-4,-5,-7,-9,-8,]),'VAR':([10,18,],[17,19,]),'EQ':([1,2,14,15,16,17,19,],[-6,6,-4,-5,-7,-9,-8,]),'MINUS':([1,2,14,15,16,17,19,],[-6,9,-4,-5,-7,-9,-8,]),'$end':([3,11,12,13,],[0,-2,-3,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'A':([10,],[16,]),'cterm':([0,8,9,],[1,14,15,]),'equation':([0,],[3,]),'expression':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> equation","S'",1,None,None,None),
  ('equation -> expression LEQ NUMBER','equation',3,'p_equation_leq','/home_local/souy/Desktop/parser/SAT_Poly/SAT/simpleparse.py',15),
  ('equation -> expression GEQ NUMBER','equation',3,'p_equation_geq','/home_local/souy/Desktop/parser/SAT_Poly/SAT/simpleparse.py',19),
  ('equation -> expression EQ NUMBER','equation',3,'p_equation_eq','/home_local/souy/Desktop/parser/SAT_Poly/SAT/simpleparse.py',23),
  ('expression -> expression PLUS cterm','expression',3,'p_expression_plus','/home_local/souy/Desktop/parser/SAT_Poly/SAT/simpleparse.py',27),
  ('expression -> expression MINUS cterm','expression',3,'p_expression_minus','/home_local/souy/Desktop/parser/SAT_Poly/SAT/simpleparse.py',31),
  ('expression -> cterm','expression',1,'p_expression_cterm','/home_local/souy/Desktop/parser/SAT_Poly/SAT/simpleparse.py',38),
  ('cterm -> NUMBER TIMES A','cterm',3,'p_cterm_cof','/home_local/souy/Desktop/parser/SAT_Poly/SAT/simpleparse.py',45),
  ('A -> A TIMES VAR','A',3,'p_A_var','/home_local/souy/Desktop/parser/SAT_Poly/SAT/simpleparse.py',51),
  ('A -> VAR','A',1,'p_A','/home_local/souy/Desktop/parser/SAT_Poly/SAT/simpleparse.py',56),
]
